### ISSUE TITLE
which thing to open vro after steup

### ISSUE THREAD

**Issue by NExxUss-07** [NotTiie/XSpammer#1]

**Comment by NotTiie** [comment]
open either proxy_support.py or proxyless.py

**Comment by NExxUss-07** [comment]
![image](https://user-images.githubusercontent.com/98755775/153748278-dd7e69d8-02c8-495f-b3f2-5bdeff546026.png)

**Comment by NExxUss-07** [comment]
> ![image](https://user-images.githubusercontent.com/98755775/153748278-dd7e69d8-02c8-495f-b3f2-5bdeff546026.png)

vro what this saying ?

**Comment by NotTiie** [comment]
delete line 4
